version: '3.8'

services:
  db:
    image: postgres:12.2-alpine
    container_name: "db-comments"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=comments_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  api:
    build: .
    container_name: api-server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DBNAME=comments_db
      - SSL_MODE=disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
